name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9"]
        exclude:
          # exclude macos python3.9 as it seems to fail because of everything
          - os: "macos-latest"
            python-version: "3.9"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64exclude from 

      - name: Install
        run: |
          pip install -e .
          # Dirty hack to get periodic decomposition installed, as no package is available
          pip install git+https://github.com/TAdeJong/moisan2011.git#egg=moisan2011
          pip install -r requirements_test.txt          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --statistics
      - name: Run tests
        run: |
          pytest
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2

